En este aparatado lo que vamos a hacer es calcular las distancias entre puntos de aforamiento. 
A la vez vamos a unir las bases de datos de aforamientos

In [1]:
# Se unen las bases de datos de los aforadores y sus contajes y por mes y día de la semana que hemos descargado por años a una única base de datos. 

import pandas as pd

lista_años = ['2024','2023','2022','2021','2020','2019','2018','2017']
ruta_base = r"C:\Users\vpere\Desktop\Especialitzacio\Proyecto\ORDENADOS\aforo movilidad bcn\detalle aforadores de movilidad bcn/"
ruta_base= ruta_base.replace('\\','/')
dfs = []

for año in lista_años:
    ruta = f"{ruta_base}{año}.csv"
    df = pd.read_csv(ruta)
    df["año"] = año   
    dfs.append(df)

df_resumen_aforament_bcn = pd.concat(dfs, ignore_index=True)



df_resumen_aforament_bcn.to_excel(
    ruta_base+'resumen_aforament_bcn.xlsx',
    sheet_name="aforament_bcn",
    index=False
)

In [2]:
df_resumen_aforament_bcn

         Any Id_aforament  Mes  Codi_tipus_dia Desc_tipus_dia Valor_IMD   año
0       2024        10001    1               1        dilluns      8665  2024
1       2024        10001    1               2     laborables      8867  2024
2       2024        10001    1               3      divendres      9127  2024
3       2024        10001    1               4       dissabte      8063  2024
4       2024        10001    1               5       diumenge      6234  2024
...      ...          ...  ...             ...            ...       ...   ...
343670  2017        20085   12               1        Dilluns        63  2017
343671  2017        20085   12               2      Laborable       120  2017
343672  2017        20085   12               3      Divendres       103  2017
343673  2017        20085   12               4       Dissabte        95  2017
343674  2017        20085   12               5       Diumenge       120  2017

[343675 rows x 7 columns]

In [3]:
# Los equipos aforados los disponemos por año con lo que se crea una df de todos los años
import pandas as pd

lista_años = ['2024','2023','2022','2021','2020','2019','2018','2017']
ruta_base = r'C:\Users\vpere\Desktop\Especialitzacio\Proyecto\ORDENADOS\aforo movilidad bcn\equipos aforos/'
ruta_base= ruta_base.replace('\\','/')
dfs2 = []

for año in lista_años:
    ruta = f"{ruta_base}{año}_aforament_descripcio.csv"
    df = pd.read_csv(ruta, encoding='latin1',on_bad_lines='skip')
    df["año"] = año   
    dfs2.append(df)

resumen_equips_aforats_bcn = pd.concat(dfs2, ignore_index=True)



resumen_equips_aforats_bcn.to_excel(
    ruta_base+'resumen_equips_aforats_bcn.xlsx',
    sheet_name="equips_aforament_bcn",
    index=False
)

In [4]:
resumen_equips_aforats_bcn

,Id_aforament,Desc_aforament,Codi_tipus_aforament,Desc_tipus_aforament,Num_carrils,Codi_districte,Codi_Barri,Codi_tipus_equip_mesura,Desc_tipus_equip_mesura,Longitud,Latitud,X_ETRS89,Y_ETRS89,año,Codi_barri,"ï»¿""Id_aforament"""
0,10001,ARAGÃ - NAVAS (Llobregat),1,TrÃ nsit,2,10.0,65.0,1.0,Espira,2.190735,41.411680,432364.559,4584775.026,2024,NaN,NaN
1,10002,BAC DE RODA - BOLIVIA (Pujada),1,TrÃ nsit,3,10.0,71.0,1.0,Espira,2.198983,41.411337,433053.504,4584730.520,2024,NaN,NaN
2,10005,ARAGÃ - BILBAO (BesÃ²s),1,TrÃ nsit,2,10.0,65.0,1.0,Espira,2.191886,41.412286,432461.330,4584841.413,2024,NaN,NaN
3,10007,CANTÃBRIA - GUIPÃSCOA (Baixada),1,TrÃ nsit,2,10.0,72.0,1.0,Espira,2.201899,41.419286,433305.332,4585610.784,2024,NaN,NaN
4,10008,CANTÃBRIA - GUIPÃSCOA (Pujada),1,TrÃ nsit,2,10.0,72.0,1.0,Espira,2.201063,41.420043,433236.312,4585695.525,2024,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5851,20165,PORTAL DE LA PAU - PG. COLOM,2,bicis,1,1.0,NaN,1.0,Espira,2.178535,41.376538,431307.880,4580883.240,2017,2.0,NaN
5852,20166,PL. DRASSANES (BESÃS),2,bicis,1,3.0,NaN,1.0,Espira,2.174810,41.376383,430996.260,4580868.990,2017,11.0,NaN
5853,20167,PL. DRASSANES (LLOBREGAT),2,bicis,1,3.0,NaN,1.0,Espira,2.174786,41.376379,430994.260,4580868.510,2017,11.0,NaN
5854,20168,AV. MARIA CRISTINA - RIUS I TAULET,2,bicis,1,0.0,NaN,NaN,NaN,2.157086,41.383003,429521.260,4581618.180,2017,0.0,NaN
5855,20169,AV. MARIA CRISTINA - PL. ESPANYA,2,bicis,1,0.0,NaN,NaN,NaN,2.149252,41.374535,428856.990,4580684.450,2017,0.0,NaN

In [5]:
# Quitamos los carriles bicis porque no nos interesan para el estudio

equips_aforats_sin_bici_bcn=resumen_equips_aforats_bcn[resumen_equips_aforats_bcn['Desc_tipus_aforament']!='bicis']

equips_aforats_sin_bici_bcn.to_excel(
    ruta_base+'resumen_equips_aforats_sin_bici_bcn.xlsx',
    sheet_name="equips_aforament_bcn",
    index=False
)

In [6]:
equips_aforats_sin_bici_bcn

,Id_aforament,Desc_aforament,Codi_tipus_aforament,Desc_tipus_aforament,Num_carrils,Codi_districte,Codi_Barri,Codi_tipus_equip_mesura,Desc_tipus_equip_mesura,Longitud,Latitud,X_ETRS89,Y_ETRS89,año,Codi_barri,"ï»¿""Id_aforament"""
0,10001,ARAGÃ - NAVAS (Llobregat),1,TrÃ nsit,2,10.0,65.0,1.0,Espira,2.190735,41.411680,432364.559,4584775.026,2024,NaN,NaN
1,10002,BAC DE RODA - BOLIVIA (Pujada),1,TrÃ nsit,3,10.0,71.0,1.0,Espira,2.198983,41.411337,433053.504,4584730.520,2024,NaN,NaN
2,10005,ARAGÃ - BILBAO (BesÃ²s),1,TrÃ nsit,2,10.0,65.0,1.0,Espira,2.191886,41.412286,432461.330,4584841.413,2024,NaN,NaN
3,10007,CANTÃBRIA - GUIPÃSCOA (Baixada),1,TrÃ nsit,2,10.0,72.0,1.0,Espira,2.201899,41.419286,433305.332,4585610.784,2024,NaN,NaN
4,10008,CANTÃBRIA - GUIPÃSCOA (Pujada),1,TrÃ nsit,2,10.0,72.0,1.0,Espira,2.201063,41.420043,433236.312,4585695.525,2024,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5718,17005,AV. DIAGONAL - PERE IV (Pujada),1,trÃ nsit,2,10.0,NaN,1.0,Espira,2.200160,41.406740,433147.150,4584219.310,2017,68.0,NaN
5719,17006,"SORTIDA 24, RONDA LITORAL SENTIT BESÃS",1,trÃ nsit,1,10.0,NaN,1.0,Espira,2.218197,41.405554,434653.560,4584073.860,2017,68.0,NaN
5720,17007,JOSEP PLÃ - PG. TAULAT,1,trÃ nsit,3,10.0,NaN,1.0,Espira,2.215944,41.408745,434468.510,4584429.840,2017,71.0,NaN
5721,17008,PG. VALL D'HEBRON - C. DE TICIÃ (LLOBREGAT),1,trÃ nsit,2,10.0,NaN,1.0,Espira,2.138465,41.416558,428001.320,4585358.760,2017,68.0,NaN
5722,17009,RDA. DALT SORTIDA 6 LLOBREGAT,1,trÃ nsit,1,5.0,NaN,1.0,Espira,2.138241,41.417147,427983.230,4585424.330,2017,71.0,NaN

In [7]:

# Quitamos del archivo resumen_aforament_bcn.xlsx las bicis
# df_filtrado = df_base[df_base['id'].isin(df_ids['id'])]

df_aforament_filtrado_sin_bici=df_resumen_aforament_bcn[df_resumen_aforament_bcn['Id_aforament'].isin(equips_aforats_sin_bici_bcn['Id_aforament'])]

df_aforament_filtrado_sin_bici.to_excel(
    ruta_base+'aforament_filtrado_sin_bici.xlsx',
    sheet_name="aforament_filtrado_sin_bici",
    index=False
)

In [8]:
df_aforament_filtrado_sin_bici

         Any Id_aforament  Mes  Codi_tipus_dia Desc_tipus_dia Valor_IMD   año
0       2024        10001    1               1        dilluns      8665  2024
1       2024        10001    1               2     laborables      8867  2024
2       2024        10001    1               3      divendres      9127  2024
3       2024        10001    1               4       dissabte      8063  2024
4       2024        10001    1               5       diumenge      6234  2024
...      ...          ...  ...             ...            ...       ...   ...
338810  2017        17009   12               1        Dilluns     12260  2017
338811  2017        17009   12               2      Laborable     12299  2017
338812  2017        17009   12               3      Divendres     12413  2017
338813  2017        17009   12               4       Dissabte      9022  2017
338814  2017        17009   12               5       Diumenge      7739  2017

[337255 rows x 7 columns]

Vamos a visualizar los puntos de los aforadores en el mapa de Barcelona

In [9]:
# Ahora lo que vamos a hacer es poner los puntos de los equipos aforadores en un mapa.


import geopandas as gpd
from shapely.geometry import Point

# Crear geometría a partir de latitud y longitud. Point(longitud, latitud) crea un punto geográfico.
geometry = [Point(xy) for xy in zip(equips_aforats_sin_bici_bcn["Longitud"], equips_aforats_sin_bici_bcn["Latitud"])]

# Lo hacemos convirtiendo el Dataframe de equips_aforats_sin_bici_bcn en un GeoDataFrame. EPSG:4326 es el sistema de referencia geográfico estándar. 
geo_equips_aforats_sin_bici_bcn = gpd.GeoDataFrame(equips_aforats_sin_bici_bcn, geometry=geometry, crs="EPSG:4326")

In [10]:
geo_equips_aforats_sin_bici_bcn

,Id_aforament,Desc_aforament,Codi_tipus_aforament,Desc_tipus_aforament,Num_carrils,Codi_districte,Codi_Barri,Codi_tipus_equip_mesura,Desc_tipus_equip_mesura,Longitud,Latitud,X_ETRS89,Y_ETRS89,año,Codi_barri,"ï»¿""Id_aforament""",geometry
0,10001,ARAGÃ - NAVAS (Llobregat),1,TrÃ nsit,2,10.0,65.0,1.0,Espira,2.190735,41.411680,432364.559,4584775.026,2024,NaN,NaN,POINT (2.19074 41.41168)
1,10002,BAC DE RODA - BOLIVIA (Pujada),1,TrÃ nsit,3,10.0,71.0,1.0,Espira,2.198983,41.411337,433053.504,4584730.520,2024,NaN,NaN,POINT (2.19898 41.41134)
2,10005,ARAGÃ - BILBAO (BesÃ²s),1,TrÃ nsit,2,10.0,65.0,1.0,Espira,2.191886,41.412286,432461.330,4584841.413,2024,NaN,NaN,POINT (2.19189 41.41229)
3,10007,CANTÃBRIA - GUIPÃSCOA (Baixada),1,TrÃ nsit,2,10.0,72.0,1.0,Espira,2.201899,41.419286,433305.332,4585610.784,2024,NaN,NaN,POINT (2.2019 41.41929)
4,10008,CANTÃBRIA - GUIPÃSCOA (Pujada),1,TrÃ nsit,2,10.0,72.0,1.0,Espira,2.201063,41.420043,433236.312,4585695.525,2024,NaN,NaN,POINT (2.20106 41.42004)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5718,17005,AV. DIAGONAL - PERE IV (Pujada),1,trÃ nsit,2,10.0,NaN,1.0,Espira,2.200160,41.406740,433147.150,4584219.310,2017,68.0,NaN,POINT (2.20016 41.40674)
5719,17006,"SORTIDA 24, RONDA LITORAL SENTIT BESÃS",1,trÃ nsit,1,10.0,NaN,1.0,Espira,2.218197,41.405554,434653.560,4584073.860,2017,68.0,NaN,POINT (2.2182 41.40555)
5720,17007,JOSEP PLÃ - PG. TAULAT,1,trÃ nsit,3,10.0,NaN,1.0,Espira,2.215944,41.408745,434468.510,4584429.840,2017,71.0,NaN,POINT (2.21594 41.40875)
5721,17008,PG. VALL D'HEBRON - C. DE TICIÃ (LLOBREGAT),1,trÃ nsit,2,10.0,NaN,1.0,Espira,2.138465,41.416558,428001.320,4585358.760,2017,68.0,NaN,POINT (2.13846 41.41656)
5722,17009,RDA. DALT SORTIDA 6 LLOBREGAT,1,trÃ nsit,1,5.0,NaN,1.0,Espira,2.138241,41.417147,427983.230,4585424.330,2017,71.0,NaN,POINT (2.13824 41.41715)

Lo que vamos a hacer es calcular distancias entre puntos de aforament por las calles de Barcelona.

Para calcular los kilómetros recorridos de forma realista no se ha utilizado distancia euclidiana, sino distancia sobre red viaria. Para ello se ha descargado la red de conducción de Barcelona desde OpenStreetMap mediante OSMnx y se ha aplicado el algoritmo de Dijkstra para obtener la distancia mínima entre nodos asociada a cada equipo de aforo.

En el siguiente paso lo que hacemos es descargar:

* Todas las calles transitables en coche

* En formato grafo (nodos e intersecciones)


Un grafo tiene:

* Nodos (intersecciones)

* Aristas (tramos de calle)

* Cada arista tiene una longitud real en metros

In [11]:
import osmnx as ox

# Descargar red de conducción (drive). Lo que hacemos es descargar las red viaria de las calles de Barcelona en modo grafo asignado una nodo y aristas a cada calle
red_conduccion = ox.graph_from_place("Barcelona, Spain", network_type="drive")

In [12]:
red_conduccion

Convertir equipos en nodos de red:

Cada equipo debe asociarse al nodo más cercano de la red viaria que nos hemos descargado con osmnx. Porque el cálculo de ruta se hace entre nodos del grafo.

* Mira la coordenada de tu equipo de aforo.

* Busca cuál es la intersección de calle más cercana.

* Devuelve el ID de esa intersección.


Es decir el equipo no está exactamente en un nodo del grafo, entonces se "engancha" al nodo más cercano para poder calcular las rutas. y el nearest_node es el id que se le asigna al equipo para después calcular las distancias

In [13]:
# Obtener nodos más cercanos
geo_equips_aforats_sin_bici_bcn["nearest_node"] = geo_equips_aforats_sin_bici_bcn.apply(
    lambda row: ox.distance.nearest_nodes(red_conduccion, row["Longitud"], row["Latitud"]),
    axis=1
)

In [14]:
geo_equips_aforats_sin_bici_bcn

,Id_aforament,Desc_aforament,Codi_tipus_aforament,Desc_tipus_aforament,Num_carrils,Codi_districte,Codi_Barri,Codi_tipus_equip_mesura,Desc_tipus_equip_mesura,Longitud,Latitud,X_ETRS89,Y_ETRS89,año,Codi_barri,"ï»¿""Id_aforament""",geometry,nearest_node
0,10001,ARAGÃ - NAVAS (Llobregat),1,TrÃ nsit,2,10.0,65.0,1.0,Espira,2.190735,41.411680,432364.559,4584775.026,2024,NaN,NaN,POINT (2.19074 41.41168),1601776198
1,10002,BAC DE RODA - BOLIVIA (Pujada),1,TrÃ nsit,3,10.0,71.0,1.0,Espira,2.198983,41.411337,433053.504,4584730.520,2024,NaN,NaN,POINT (2.19898 41.41134),618431744
2,10005,ARAGÃ - BILBAO (BesÃ²s),1,TrÃ nsit,2,10.0,65.0,1.0,Espira,2.191886,41.412286,432461.330,4584841.413,2024,NaN,NaN,POINT (2.19189 41.41229),506223397
3,10007,CANTÃBRIA - GUIPÃSCOA (Baixada),1,TrÃ nsit,2,10.0,72.0,1.0,Espira,2.201899,41.419286,433305.332,4585610.784,2024,NaN,NaN,POINT (2.2019 41.41929),559410529
4,10008,CANTÃBRIA - GUIPÃSCOA (Pujada),1,TrÃ nsit,2,10.0,72.0,1.0,Espira,2.201063,41.420043,433236.312,4585695.525,2024,NaN,NaN,POINT (2.20106 41.42004),559410527
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5718,17005,AV. DIAGONAL - PERE IV (Pujada),1,trÃ nsit,2,10.0,NaN,1.0,Espira,2.200160,41.406740,433147.150,4584219.310,2017,68.0,NaN,POINT (2.20016 41.40674),262251752
5719,17006,"SORTIDA 24, RONDA LITORAL SENTIT BESÃS",1,trÃ nsit,1,10.0,NaN,1.0,Espira,2.218197,41.405554,434653.560,4584073.860,2017,68.0,NaN,POINT (2.2182 41.40555),243341469
5720,17007,JOSEP PLÃ - PG. TAULAT,1,trÃ nsit,3,10.0,NaN,1.0,Espira,2.215944,41.408745,434468.510,4584429.840,2017,71.0,NaN,POINT (2.21594 41.40875),4485344001
5721,17008,PG. VALL D'HEBRON - C. DE TICIÃ (LLOBREGAT),1,trÃ nsit,2,10.0,NaN,1.0,Espira,2.138465,41.416558,428001.320,4585358.760,2017,68.0,NaN,POINT (2.13846 41.41656),412457668
5722,17009,RDA. DALT SORTIDA 6 LLOBREGAT,1,trÃ nsit,1,5.0,NaN,1.0,Espira,2.138241,41.417147,427983.230,4585424.330,2017,71.0,NaN,POINT (2.13824 41.41715),412453392

Calcular distancia al equipo más cercano

In [15]:
import networkx as nx

distancias_minimas = []

nodos = geo_equips_aforats_sin_bici_bcn["nearest_node"].tolist()

for origen in nodos:
    
    # Calcula TODAS las distancias desde este origen
    lengths = nx.single_source_dijkstra_path_length(
        red_conduccion,
        origen,
        weight="length"
    )
    
    # Filtramos solo nodos que sean equipos de aforo
    distancias_a_equipos = [
        lengths[nodo] 
        for nodo in nodos 
        if nodo in lengths and nodo != origen
    ]
    
    if distancias_a_equipos:
        distancias_minimas.append(min(distancias_a_equipos))
    else:
        distancias_minimas.append(None)

geo_equips_aforats_sin_bici_bcn["distancia_equipo_mas_cercano_m"] = distancias_minimas

In [17]:
geo_equips_aforats_sin_bici_bcn

,Id_aforament,Desc_aforament,Codi_tipus_aforament,Desc_tipus_aforament,Num_carrils,Codi_districte,Codi_Barri,Codi_tipus_equip_mesura,Desc_tipus_equip_mesura,Longitud,Latitud,X_ETRS89,Y_ETRS89,año,Codi_barri,"ï»¿""Id_aforament""",geometry,nearest_node,distancia_equipo_mas_cercano_m
0,10001,ARAGÃ - NAVAS (Llobregat),1,TrÃ nsit,2,10.0,65.0,1.0,Espira,2.190735,41.411680,432364.559,4584775.026,2024,NaN,NaN,POINT (2.19074 41.41168),1601776198,81.924372
1,10002,BAC DE RODA - BOLIVIA (Pujada),1,TrÃ nsit,3,10.0,71.0,1.0,Espira,2.198983,41.411337,433053.504,4584730.520,2024,NaN,NaN,POINT (2.19898 41.41134),618431744,454.027229
2,10005,ARAGÃ - BILBAO (BesÃ²s),1,TrÃ nsit,2,10.0,65.0,1.0,Espira,2.191886,41.412286,432461.330,4584841.413,2024,NaN,NaN,POINT (2.19189 41.41229),506223397,121.748549
3,10007,CANTÃBRIA - GUIPÃSCOA (Baixada),1,TrÃ nsit,2,10.0,72.0,1.0,Espira,2.201899,41.419286,433305.332,4585610.784,2024,NaN,NaN,POINT (2.2019 41.41929),559410529,23.608065
4,10008,CANTÃBRIA - GUIPÃSCOA (Pujada),1,TrÃ nsit,2,10.0,72.0,1.0,Espira,2.201063,41.420043,433236.312,4585695.525,2024,NaN,NaN,POINT (2.20106 41.42004),559410527,23.608065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5718,17005,AV. DIAGONAL - PERE IV (Pujada),1,trÃ nsit,2,10.0,NaN,1.0,Espira,2.200160,41.406740,433147.150,4584219.310,2017,68.0,NaN,POINT (2.20016 41.40674),262251752,286.772075
5719,17006,"SORTIDA 24, RONDA LITORAL SENTIT BESÃS",1,trÃ nsit,1,10.0,NaN,1.0,Espira,2.218197,41.405554,434653.560,4584073.860,2017,68.0,NaN,POINT (2.2182 41.40555),243341469,74.093674
5720,17007,JOSEP PLÃ - PG. TAULAT,1,trÃ nsit,3,10.0,NaN,1.0,Espira,2.215944,41.408745,434468.510,4584429.840,2017,71.0,NaN,POINT (2.21594 41.40875),4485344001,458.970630
5721,17008,PG. VALL D'HEBRON - C. DE TICIÃ (LLOBREGAT),1,trÃ nsit,2,10.0,NaN,1.0,Espira,2.138465,41.416558,428001.320,4585358.760,2017,68.0,NaN,POINT (2.13846 41.41656),412457668,58.482415
5722,17009,RDA. DALT SORTIDA 6 LLOBREGAT,1,trÃ nsit,1,5.0,NaN,1.0,Espira,2.138241,41.417147,427983.230,4585424.330,2017,71.0,NaN,POINT (2.13824 41.41715),412453392,135.333524

Las distancias se han calculado utilizando la red viaria descargada mediante OSMnx, donde cada arista incorpora su longitud real en metros. El algoritmo de Dijkstra ponderado por el atributo "length" permite obtener la distancia real recorrida por carretera entre puntos.

In [20]:
geo_equips_aforats_sin_bici_bcn["distancia_km"] = (
    geo_equips_aforats_sin_bici_bcn["distancia_equipo_mas_cercano_m"] / 1000
)

In [21]:

geo_equips_aforats_sin_bici_bcn.to_excel(
    ruta_base+'geo_equips_aforats_sin_bici_bcn.xlsx',
    sheet_name="geo_equips_aforats_sin_bici_bcn",
    index=False
)